<?php

namespace Jsanbae\SIIAPI\Constants;

class DocTypes
{
    const FACTURA_ELECTRONICA = 33;
    const FACTURA_NO_AFECTA_O_EXENTA_ELECTRONICA = 34;
    const FACTURA_COMPRA_ELECTRONICA = 46;
    const FACTURA_EXPORTACION_ELECTRONICA = 110;
    const NOTA_DEBITO_ELECTRONICA = 56;
    const NOTA_CREDITO_ELECTRONICA = 61;
    const NOTA_DEBITO_ELECTRONICA_EXPORTACION = 111;
    const NOTA_CREDITO_ELECTRONICA_EXPORTACION = 112;
    const GUIA_DESPACHO_ELECTRONICA = 52;
    const BOLETA_ELECTRONICA = 39;
    const BOLETA_NO_AFECTA_O_EXENTA_ELECTRONICA = 41;
    const BOLETA_EXENTA_ELECTRONICA = 43;
    const BOLETA_HONORIARIOS = 99;
    const BOLETA_HONORIARIOS_ELECTRONICA = 100;

}
